---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zedpayhe/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -f index.html $DEPLOYPATH/index.html
    - /bin/sh -c 'if [ -f download.php ]; then /bin/cp -f download.php "$DEPLOYPATH/download.php"; fi'
